---

- name: Server initialization configuration
  hosts: all
  remote_user: root
  roles:
    - common

- name: Install Tomcat
  hosts: all
  remote_user: root
  roles:
    - tomcat

- name: Install end 
  hosts: all
  remote_user: root
  roles:
    - end
