---
- name: download tomcat install package 
  get_url:
      url: http://10.199.88.248/noc/FareDisplaySystem/apache-tomcat-7.0.70.tar.gz
      dest: /usr/local/bin/apache-tomcat-7.0.70.tar.gz
      force: yes

- name: tar tomcat install package
#  command: /bin/tar -xzvf /usr/local/bin/apache-tomcat-7.0.70.tar.gz -C /usr/local/
  unarchive: src=/usr/local/bin/apache-tomcat-7.0.70.tar.gz  dest=/data/ copy=no

- name: rename apache-tomcat-7.0.70 to tomcat-7.0.70
  shell: mv /data/apache-tomcat-7.0.70 /data/tomcat-7.0.70

- name: create tomcat config file
  template: src=server.xml.j2 dest=/data/tomcat-7.0.70/conf/server.xml

- name: set tomcat auto start
  #shell: echo "nohup /data/tomcat-7.0.70/bin/startup.sh &" >> /etc/rc.local
  shell: echo "/data/tomcat-7.0.70/bin/startup.sh > /dev/null" >> /etc/rc.local

- name: start tomcat service
  #shell: nohup /usr/local/tomcat-7.0.70/bin/startup.sh &
  shell: /data/tomcat-7.0.70/bin/startup.sh > /dev/null

